### ISSUE TITLE
Great Code

### ISSUE THREAD

**Issue by janus** [maierfelix/mini-js#2]
Your code is clean and easy to follow. I enjoyed it, and I have learnt a lot. But it looks like you repeated the below:

      // | # ||
      else if (ch == "|") {
        if (ch + second == "||") {
          next();
          processToken(tokens, ch + second, line, column);
        } else {
          processToken(tokens, ch, line, column);
        }
}

**Comment by maierfelix** [comment]
Glad you enjoyed it, fixed with https://github.com/maierfelix/mini-js/commit/b71e67736b6dac9a217b648930f51d897e829d0f
